### ISSUE TITLE
Not embedding text in images where possible for accessibility

### ISSUE THREAD

**Issue by vtwkam1** [GitWray1/niceRplots#1]
In [the Gov analysis function guide](https://analysisfunction.civilservice.gov.uk/policy-store/data-visualisation-charts/#section-6), they recommend including the titles, subtitles, captions and data source text within the body text of the page rather than embedded in the image for better accessibility, and putting the title and subtitle in appropriate header levels too. Obviously this means that the graphs can be taken out of context but they say doing it this way prioritises accessibility. 

Currently, title, subtitle, caption and data source in ggplot NICE theme is embedded within the image

**Comment by GitWray1** [comment]
This issue has now been resolved with the addition of the chart accessibility section in the cookbook
