### ISSUE TITLE
Clarify loading data step

### ISSUE THREAD

**Issue by vtwkam1** [GitWray1/niceRplots#2]
https://github.com/GitWray1/niceRplots/blob/135c7c58973f8133c3eb92c61fac10345fd05d93/vignettes/NICE_cookbook.Rmd#L162-L163

Is the idea here to demonstrate loading data? In which case maybe clarify that the data is assumed to be in the same folder and named "DOACS_data.csv".

Noticed that the chunk isn't run and that the DOACs data is lazily-loaded when the package is loaded.

**Comment by GitWray1** [comment]
I have now clarified the loading step, making it clear that this is purely for demonstration purposes
