### ISSUE TITLE
Get warning recurring warning when this is run

### ISSUE THREAD

**Issue by vtwkam1** [GitWray1/niceRplots#3]
https://github.com/GitWray1/niceRplots/blob/135c7c58973f8133c3eb92c61fac10345fd05d93/vignettes/NICE_cookbook.Rmd#L40

When line run alone, get never-ending warning message: "Warning in cr_get_ratio(.x, .y): Aim for a value of 4.5 or higher."

The .rmd still knits, but includes a huge chunk with this same warning message repeated over and over again.

**Comment by GitWray1** [comment]
Hopefully should be resolved, removed the load_all() call and replaced with library(niceRplots).
